// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA8cUEzMjtTQI-UjFbmyTe9iOD9SLiEqA',
    appId: '1:762112815097:web:f1ca8413ed4dc42d6f5728',
    messagingSenderId: '762112815097',
    projectId: 'ltdd-d560f',
    authDomain: 'ltdd-d560f.firebaseapp.com',
    storageBucket: 'ltdd-d560f.firebasestorage.app',
    measurementId: 'G-DLPPG2948V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvyej09GQzSgzK6m6VQ3LN0mgzj-osJ3s',
    appId: '1:762112815097:android:c4c9a3ad0bdce19f6f5728',
    messagingSenderId: '762112815097',
    projectId: 'ltdd-d560f',
    storageBucket: 'ltdd-d560f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87wwFigTgWpu6u6GzLuh2ooFcPn-xX0s',
    appId: '1:762112815097:ios:a6fc6f1ff2cf2d1d6f5728',
    messagingSenderId: '762112815097',
    projectId: 'ltdd-d560f',
    storageBucket: 'ltdd-d560f.firebasestorage.app',
    iosClientId: '762112815097-bn6arkj2c2avqe23cgan5pgfkfub2afs.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB87wwFigTgWpu6u6GzLuh2ooFcPn-xX0s',
    appId: '1:762112815097:ios:a6fc6f1ff2cf2d1d6f5728',
    messagingSenderId: '762112815097',
    projectId: 'ltdd-d560f',
    storageBucket: 'ltdd-d560f.firebasestorage.app',
    iosClientId: '762112815097-bn6arkj2c2avqe23cgan5pgfkfub2afs.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA8cUEzMjtTQI-UjFbmyTe9iOD9SLiEqA',
    appId: '1:762112815097:web:1c0011ab8aee9dd16f5728',
    messagingSenderId: '762112815097',
    projectId: 'ltdd-d560f',
    authDomain: 'ltdd-d560f.firebaseapp.com',
    storageBucket: 'ltdd-d560f.firebasestorage.app',
    measurementId: 'G-SHW4GHR465',
  );
}
